### ISSUE TITLE
call qzCompress to compress a 8KB data block with hardware mode, but decompress with software mode meet errors "invalid block type"

### ISSUE THREAD

**Issue by leonzzz** [intel/QATzip#44] opened 2020-09-16 15:56 UTC
There is 3 QAT acceleration device(s) in the system:
 qat_dev0 - type: c6xx,  inst_id: 0,  node_id: 0,  bsf: 0000:33:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev1 - type: c6xx,  inst_id: 1,  node_id: 0,  bsf: 0000:34:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev2 - type: c6xx,  inst_id: 2,  node_id: 0,  bsf: 0000:35:00.0,  #accel: 5 #engines: 10 state: up

1) qzCompress is called with parameter last being equal to 1. 
 (did not change any config and apply QAT hardware instance to run compress)

  A 8192 bytes data block is compressed to 7809 bytes

2) qzDecompress is called via codes below (Zlib1.2.11's inflate(stream, Z_SYNC_FLUSH) is called eventually):

QzSession_T *sess
sess->hw_session_stat = QZ_NO_HW;    // so that qzDecompress could switch to software mode
sess->thd_sess_stat = QZ_OK;   // ensure session is normal

deCompress is called and run-time error log looks like :

qzDecompress data_fmt: 2
decompression src_len=7809, hdr->extra.qz_e.src_sz = 8192, g_process.qz_init_status = 0, sess->hw_session_stat = 11, isQATProcessable = 1, switch to software.
Start qzSWDecompressMultiGzip: src_len 7809 dest_len 8192
decomp_sw data_fmt: 2

****** inflate init done with win_bits: 31 *****
ERR: inflate failed with Z_DATA_ERROR
Exit qzSWDecompress total_in: 7802 total_out: 8192 avail_in: 7 avail_out: 0 msg: invalid block type src_len: 0 dest_len: 0
Exit qzSWDecompressMultiGzip: src_len 0 dest_len 0

**Comment by leonzzz** [comment] 2020-09-16 16:08
Pls help check whether there is incompatibility issue between QAT and Zlib1.2.11 or current codes of using qatZip functions are wrong?

**Comment by leonzzz** [comment] 2020-09-16 16:12
Pls help check whether there is incompatibility issue between QAT and Zlib1.2.11 or current codes of using qatZip functions are wrong?

**Comment by leonzzz** [comment] 2020-09-16 16:16
There is 3 QAT acceleration device(s) in the system:
 qat_dev0 - type: c6xx,  inst_id: 0,  node_id: 0,  bsf: 0000:33:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev1 - type: c6xx,  inst_id: 1,  node_id: 0,  bsf: 0000:34:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev2 - type: c6xx,  inst_id: 2,  node_id: 0,  bsf: 0000:35:00.0,  #accel: 5 #engines: 10 state: up

**Comment by zhangp8x** [comment] 2020-10-19 03:18
Hi:

We have tried to reproduce this issue for several weeks, but can not reproduce. Since you can not provide source codes, and target file, we have to close this ticket in the coming weeks. If you still have any question, please reopen this ticket.

BRs/Thx.

**Closed** 2020-10-23 07:09 UTC

**Comment by leonzzz** [comment] 2021-01-23 13:24
Update:
when software instances, which are calling zlib, uncompress compressed data (with a header and 8 bytes of footer) generated by QAT hardware instance, the default 8 footer (of 8 bytes) should be excluded, else, zlib cannot handle remain(less than 8) bytes correctly.
This should be the RCA.

**Comment by zhangp8x** [comment] 2021-01-25 01:09
@leonzzz 
Thank  you for your reply, we will try internally.

**Comment by zhangp8x** [comment] 2021-02-07 01:56
@leonzzz 

From my side, I use $QZ_ROOT/utils with a file that can be compressed into 7678. I got following results.

```
qzDecompress data_fmt: 2
decompression src_len=7678, hdr->extra.qz_e.src_sz = 8192, g_process.qz_init_status =                                                                                                                                               11, sess->hw_session_stat = 11, isQATProcessable = 1, switch to software.
Start qzSWDecompressMultiGzip: src_len 7678 dest_len 38390

```

If you are using $QZ_ROOT/utils, please do not change the source codes, just disable QAT by using:

`service qat_service stop`

or unbind the qat hardware, so that you can use software compress or decompress.


But it seems that you are not using $QZ_ROOT/utils as your test application and we can not reproduce this issue in our side, keep this issue as closed.

If issue still happened, please provide more detailed information, e.g. `source codes and source file `, then we can do further investigation.

**Comment by leonzzz** [comment] 2021-02-16 04:10
Our all compressed blocks size are 8KB. 
(all mem buffer sizes are 8KB based too)

**Comment by zhangp8x** [comment] 2021-02-18 02:08
@leonzzz 
Still can not reproduce this issue, seems you have changed:

1. Function `int qzSetupSession(QzSession_T *sess, QzSessionParams_T *params)`  and let it return QZ_NO_HW.
2. And `sess->thd_sess_stat = QZ_OK; // ensure session is normal` 

In which function do you change `sess->thd_sess_stat` ? The QATzip use this value to define the software compression behaver.

If you want to test software compression/decompression, you can use `service qat_service stop` instead of code changing.
